name: Build

on:
  push:
    branches: [ main ]
  pull_request:

jobs:
  build:
    runs-on: macos-26
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Install Carthage
        run: brew install carthage

      - name: Carthage bootstrap
        run: carthage bootstrap --use-xcframeworks --platform iOS,tvOS

      - name: iOS build
        run: |
          xcodebuild \
            -project Strimr.xcodeproj \
            -scheme Strimr \
            -destination 'platform=iOS Simulator,name=iPhone 17' \
            -configuration Debug \
            -derivedDataPath build/DerivedData \
            build

      - name: tvOS build
        run: |
          xcodebuild \
            -project Strimr.xcodeproj \
            -scheme Strimr-tvOS \
            -destination 'platform=tvOS Simulator,name=Apple TV 4K (3rd generation)' \
            -configuration Debug \
            -derivedDataPath build/DerivedData \
            build
